/**
 * Recognising a uuid.
 *
 * Every key in this schema is a uuid generated by Postgres, so anything else
 * arriving as an id is a client bug — a stale dropdown, a hand-typed path.
 * Checking the shape before querying matters: passing a non-uuid to a `where
 * id = ...` makes Postgres raise "invalid input syntax for type uuid", which
 * would surface as a 502 when the honest answer is that no such row exists.
 */

const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** True when the value looks like a uuid Postgres would accept. */
export function isUuid(value: unknown): value is string {
  return typeof value === "string" && UUID_PATTERN.test(value);
}
